### ISSUE TITLE
Contribute to OOP's Python

### ISSUE THREAD

**Issue by rajatbansal01** [rajatbansal01/100daysofDSA#10]
Create classes explaining different concepts of OOP's Python in OOP's folder.

**Comment by rajatbansal01** [comment]
> Create a class with the name of book. And these are their codes. [OOP programming.zip](https://github.com/rajatbansal01/100daysofDSA/files/7276934/OOP.programming.zip)

Hey Umakshi, you can fork this repository and add your contributions, and then raise PR's.

**Comment by DanTcheche** [comment]
Hi, I can take on this issue if you assign it to me, thank you!

**Comment by rajatbansal01** [comment]
> Hi, I can take on this issue if you assign it to me, thank you!

Sure

**Comment by rohansaini886** [comment]
Hlo Rajat want to add Jupyter Notebook in Python OOP.
